import { useEffect, useMemo, useState } from 'react';

const featureNames = ['Запросов в секунду','Интервал запросов','Доля ошибок','Средний размер запроса','Среднее время обработки','Уникальные endpoint’ы','Повторяемость','Доля GET','Доля POST','Другие методы'];
const format = (value, index) => index===1||index===4 ? `${value.toFixed(1)} мс` : index===2||index===6||index>=7 ? `${(value*100).toFixed(1)}%` : index===3 ? `${(value/1024).toFixed(2)} КБ` : value.toFixed(2);
const severityLabel = { normal: 'Норма', warning: 'Предупреждение', critical: 'Критический', warming_up: 'Обучение' };
const incidentText = incident => incident.anomaly_level === 'critical' ? 'Критическое совместное отклонение признаков' : 'Отклонение от baseline-модели';
const clock = value => value ? new Intl.DateTimeFormat('ru-RU', { hour: '2-digit', minute: '2-digit', second: '2-digit' }).format(new Date(value)) : '—';
function Hint({children}) { return <span className="hint" tabIndex="0">*<span>{children}</span></span>; }
function Icon({name}) { return <span className={`icon icon-${name}`} />; }
function App() {
 const [backend,setBackend]=useState('Все backend-сервисы'); const [live,setLive]=useState(true); const [route,setRoute]=useState({host:'catalog.local',backendHost:'127.0.0.1',backendPort:'3001'}); const [routeStatus,setRouteStatus]=useState('');
 const [liveState,setLiveState]=useState(null); const [gatewayState,setGatewayState]=useState({routes:[],rules:[]}); const [connection,setConnection]=useState('loading'); const [updatedAt,setUpdatedAt]=useState(null); const analyticsUrl=import.meta.env.VITE_ANALYTICS_URL || 'http://localhost:9091'; const gatewayUrl=import.meta.env.VITE_GATEWAY_URL || 'http://localhost:8080';
 useEffect(()=>{if(!live)return;let stopped=false;const load=async()=>{try{const [analytics,routes,decisions]=await Promise.all([fetch(`${analyticsUrl}/api/state`),fetch(`${gatewayUrl}/__gateway/routes`),fetch(`${gatewayUrl}/__gateway/decisions`)]);if(!analytics.ok||!routes.ok||!decisions.ok)throw new Error();const state=await analytics.json();if(!stopped){setLiveState(state);setGatewayState({routes:(await routes.json()).routes||[],rules:(await decisions.json()).rules||[]});setConnection('online');setUpdatedAt(new Date());}}catch{if(!stopped)setConnection('offline');}};load();const id=setInterval(load,5000);return()=>{stopped=true;clearInterval(id);};},[analyticsUrl,gatewayUrl,live]);
 const services=useMemo(()=>liveState?.windows?.map(window=>window.backend)||[],[liveState]);
 const current=useMemo(()=>{const windows=liveState?.windows||[];return backend==='Все backend-сервисы'?windows[0]:windows.find(window=>window.backend===backend)||windows[0];},[liveState,backend]);
 const displayFeatures=current ? current.feature_vector.map((value,index)=>{const mean=current.baseline_mean[index];const delta=mean===0?(value===0?0:null):(value-mean)/Math.abs(mean);const state=delta!==null&&Math.abs(delta)>.2?'watch':'ok';return [featureNames[index],format(value,index),format(mean,index),delta===null?'—':`${delta>=0?'+':''}${(delta*100).toFixed(1)}%`,state,'Показатель текущего окна и baseline.'];}) : featureNames.map(name=>[name,'—','—','—','ok','Появится после первого завершённого окна telemetry.']);
 const incidents=liveState?.incidents||[];
 const saveRoute=async(e)=>{e.preventDefault();setRouteStatus('Сохраняем…');try{const r=await fetch(`${gatewayUrl}/__gateway/routes`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({host:route.host,backend_host:route.backendHost,backend_port:route.backendPort})});if(!r.ok)throw new Error();setRouteStatus('Правило сохранено');}catch{setRouteStatus('Нет связи со шлюзом');}};
 return <div className="app-shell analysis-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark">V</div><span>vector<span>gate</span></span></div><div className="workspace"><span>ОБЪЕКТ НАБЛЮДЕНИЯ</span><label className="select-wrap"><Icon name="server"/><select value={backend} onChange={e=>setBackend(e.target.value)}><option>Все backend-сервисы</option>{services.map(service=><option key={service}>{service}</option>)}</select><b>⌄</b></label></div><div className="side-focus"><span className="focus-dot"/><div><b>Анализ аномалий</b><p>Сравнение с моделью нормального трафика</p></div></div><div className="sidebar-bottom"><div className={`proxy-status ${connection}`}><span className="pulse"/>{connection==='online'?'Gateway и Analytics доступны':'Нет связи с сервисами'}<small>{updatedAt?`Данные обновлены в ${clock(updatedAt)}`:'Ожидание первого ответа'}</small></div></div></aside>
 <main><header><div><p className="eyebrow">АНАЛИЗ ТРАФИКА · {current?.backend || backend.toUpperCase()}</p><h1>Состояние потока</h1><p className="subtitle">Модель сравнивает текущий вектор признаков с нормальным поведением системы.</p></div><button className={`live-button ${live?'':'paused'}`} onClick={()=>setLive(!live)}><i/> {live?'В реальном времени':'Пауза'}</button></header>
 <section className="health-hero panel"><div className="health-copy"><p className="eyebrow">ТЕКУЩАЯ ОЦЕНКА</p><h2>{current ? (current.anomaly_level==='normal'?'Трафик выглядит нормальным':`Статус: ${current.anomaly_level}`) : 'Ожидание telemetry'}</h2><p>Совместное отклонение признаков оценивается через covariance matrix baseline-модели.</p><div className="health-tags"><span>Окно: последние 60 секунд</span><span>Модель: {current?.baseline_source || 'нет данных'}</span></div></div><div className="score-card"><div className="score-ring"><div><b>{current ? current.anomaly_score.toFixed(2) : '—'}</b><small>score</small></div></div><div><b>Индекс аномалии <Hint>Mahalanobis distance: совместное отклонение вектора от baseline.</Hint></b><p>Warning: 4.0 · Critical: 6.0</p></div></div></section>
 <section className="stats"><Stat label="ЗАПРОСОВ В СЕКУНДУ" value={current?current.requests_per_second.toFixed(2):'—'} text={current?'из текущего окна':'ожидание данных'} icon="activity"/><Stat label="ЗАПРОСОВ В ОКНЕ" value={current?current.requests:'—'} text="текущее окно" icon="link"/><Stat label="СРЕДНЕЕ ВРЕМЯ ОТВЕТА" value={current?`${current.mean_processing_ms.toFixed(1)} мс`:'—'} text="Gateway → backend" icon="clock"/><Stat label="АКТИВНЫЕ РЕШЕНИЯ" value={gatewayState.rules.length} text="правила Control Plane" icon="alert"/></section>
 <section className="panel vector-panel"><div className="panel-head"><div><h2>Вектор текущего состояния <Hint>Каждые 60 секунд прокси передаёт агрегированные признаки в аналитический сервис. Модель оценивает их совместно, а не по одному.</Hint></h2><p>Текущие показатели и их отклонение от профиля нормального трафика</p></div><span className="window-badge">ОКНО 60 С</span></div><div className="feature-table"><div className="feature-head"><span>ПРИЗНАК</span><span>СЕЙЧАС</span><span>НОРМА</span><span>ОТКЛОНЕНИЕ</span><span>СОСТОЯНИЕ</span></div>{displayFeatures.map(([name,now,base,delta,state,hint])=><div className="feature-row" key={name}><span>{name} <Hint>{hint}</Hint></span><b>{now}</b><span>{base}</span><span className={state}>{delta}</span><span><i className={`state-dot ${state}`}/>{state==='watch'?'Наблюдать':'Норма'}</span></div>)}</div></section>
 <section className="two-columns"><article className="panel route-panel"><div className="panel-head"><div><h2>Решения маршрутизации <Hint>Правила хранит Control Plane. C++-прокси применяет их локально, поэтому запрос не ждёт ответа аналитического сервиса.</Hint></h2><p>Активные правила Gateway</p></div></div><div className="route-list">{gatewayState.routes.length===0&&gatewayState.rules.length===0?<Route kind="muted" title="Правил пока нет" text="Gateway использует default backend" value="—"/>:gatewayState.routes.map(item=><Route key={item.host} kind="ok" title={item.host} text={`→ ${item.backend_host}:${item.backend_port}`} value="route"/>).concat(gatewayState.rules.map(item=><Route key={item.client_ip} kind="watch" title={`${item.action}: ${item.client_ip}`} text={item.reason||'Без причины'} value={`${item.ttl_seconds} с`}/>))}</div></article><article className="panel"><div className="panel-head"><div><h2>Изменить маршрут <Hint>Форма вызывает POST /__gateway/routes. Правило применяется proxy сразу, без его перезапуска.</Hint></h2><p>Назначить backend для HTTP-заголовка Host</p></div></div><form className="route-form" onSubmit={saveRoute}><label>Host<input value={route.host} onChange={e=>setRoute({...route,host:e.target.value})}/></label><label>Backend host<input value={route.backendHost} onChange={e=>setRoute({...route,backendHost:e.target.value})}/></label><label>Порт<input value={route.backendPort} onChange={e=>setRoute({...route,backendPort:e.target.value})}/></label><button type="submit">Сохранить правило</button><span>{routeStatus}</span></form></article></section>
 <section className="panel incidents-panel"><div className="panel-head"><div><h2>Обнаруженные отклонения <Hint>События появляются, когда вероятность текущего вектора при нормальном режиме становится ниже заданного порога.</Hint></h2><p>История текущего процесса Analytics</p></div><span className="count-badge">{incidents.length} событий</span></div><div className="incident-table"><div className="incident-head"><span>ВРЕМЯ</span><span>ОТКЛОНЕНИЕ</span><span>ЗАТРОНУТЫЙ BACKEND</span><span>ПРИОРИТЕТ</span></div>{incidents.length===0?<div className="empty-state">Событий пока нет — новые окна появятся здесь автоматически.</div>:incidents.map((incident,index)=><div className="incident-row" key={`${incident.window_end}-${index}`}><span>{clock(incident.window_end)}</span><b>{incidentText(incident)}</b><span>{incident.backend}</span><span><i className={incident.anomaly_level==='critical'?'priority-critical':'priority-low'}/>{severityLabel[incident.anomaly_level]||incident.anomaly_level}</span></div>)}</div></section></main></div>;

}
function Stat({label,value,text,icon}) { return <article className="stat-card"><div className="stat-top"><span>{label}</span><div className="icon-box"><Icon name={icon}/></div></div><strong>{value}</strong><div className="stat-bottom"><b>{text}</b></div></article>; }
function Route({kind,title,text,value}) { return <div><span className={`route-icon ${kind}`} aria-hidden="true"/><div><b>{title}</b><p>{text}</p></div><strong>{value}</strong></div>; }
export default App;
